name: "build"
on: [push, pull_request]
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Setup BATS
        uses: mig4/setup-bats@v1
        with:
          bats-version: 1.7.0

      - name: Check out code
        uses: actions/checkout@v1

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v2.0.0

      - name: Run tests
        run: bats test